# Generated by Django 2.2 on 2022-08-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='phone_no',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=17, null=True),
        ),
    ]
