# Generated by Django 2.2 on 2022-08-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220810_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostcomments',
            name='room_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='room_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
