# Generated by Django 2.2 on 2022-08-25 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220819_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvents',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('eventFequency', models.CharField(blank=True, max_length=50, null=True)),
                ('balanceFrequency', models.CharField(blank=True, max_length=50, null=True)),
                ('eventDate', models.DateField(default=django.utils.timezone.now)),
                ('eventDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('eventEndTime', models.TimeField(blank=True, null=True)),
                ('eventId', models.IntegerField(blank=True, null=True)),
                ('eventName', models.CharField(blank=True, max_length=50, null=True)),
                ('eventPhoto', models.URLField(blank=True, max_length=500, null=True)),
                ('eventstartTime', models.TimeField(blank=True, null=True)),
                ('eventDateCreated', models.DateField(default=django.utils.timezone.now)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenDecimal', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenIcon', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenName', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenSymbol', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenType', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('valueName', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical events',
                'db_table': 'events_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventFequency', models.CharField(blank=True, max_length=50, null=True)),
                ('balanceFrequency', models.CharField(blank=True, max_length=50, null=True)),
                ('eventDate', models.DateField(default=django.utils.timezone.now)),
                ('eventDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('eventEndTime', models.TimeField(blank=True, null=True)),
                ('eventId', models.IntegerField(blank=True, null=True)),
                ('eventName', models.CharField(blank=True, max_length=50, null=True)),
                ('eventPhoto', models.URLField(blank=True, max_length=500, null=True)),
                ('eventstartTime', models.TimeField(blank=True, null=True)),
                ('eventDateCreated', models.DateField(default=django.utils.timezone.now)),
                ('network', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenDecimal', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenIcon', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenName', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenSymbol', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenType', models.CharField(blank=True, max_length=50, null=True)),
                ('tokenAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('valueName', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['id'], name='events_id_e4d547_idx'),
        ),
    ]
