# Generated by Django 2.2 on 2022-08-30 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220830_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Venue'),
        ),
        migrations.AddField(
            model_name='historicalevents',
            name='venue',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Venue'),
        ),
    ]
