# Generated by Django 2.2 on 2022-09-02 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220902_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpage',
            name='subscribe_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalusersubscription',
            name='page',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='subscribe_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='page_subscription', to='api.Page'),
        ),
    ]
