# Generated by Django 2.2 on 2022-09-12 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220912_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFreeTrial',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('offer_limit', models.IntegerField(blank=True, default=1, null=True)),
                ('offer_expiration', models.IntegerField(blank=True, default=1, null=True)),
                ('trial_duration', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Page')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical free trial',
                'db_table': 'free_trial_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FreeTrial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_limit', models.IntegerField(blank=True, default=1, null=True)),
                ('offer_expiration', models.IntegerField(blank=True, default=1, null=True)),
                ('trial_duration', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trial_page', to='api.Page')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trial_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'free_trial',
            },
        ),
        migrations.AddIndex(
            model_name='freetrial',
            index=models.Index(fields=['id'], name='free_trial_id_0c9c59_idx'),
        ),
    ]
