# Generated by Django 2.2 on 2022-09-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20220912_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusersubscription',
            name='free_trial',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.FreeTrial'),
        ),
        migrations.AddField(
            model_name='historicalusersubscription',
            name='promotion_campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.PromotionCampaign'),
        ),
        migrations.AddField(
            model_name='historicalusersubscription',
            name='subscription_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='free_trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription_free_trial', to='api.FreeTrial'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='promotion_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription_promotion_campaign', to='api.PromotionCampaign'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
