# Generated by Django 2.2 on 2022-09-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220914_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalusersubscription',
            name='subscription_type',
            field=models.IntegerField(blank=True, help_text='1. Basic, 2. Bundle, 3. Promotion, 4. Trial', null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_type',
            field=models.IntegerField(blank=True, help_text='1. Basic, 2. Bundle, 3. Promotion, 4. Trial', null=True),
        ),
    ]
