# Generated by Django 2.2 on 2022-09-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20220919_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpage',
            name='page_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
