# Generated by Django 2.2 on 2022-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20220920_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusersubscription',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
