# Generated by Django 2.2 on 2022-10-04 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20220920_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='referred_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
        migrations.CreateModel(
            name='UserReferralWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('user_referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
