# Generated by Django 2.2 on 2022-10-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_creditcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='stripe_id',
            new_name='card_id',
        ),
    ]
