# Generated by Django 2.2 on 2022-10-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20221003_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
