# Generated by Django 2.2 on 2022-10-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_usertipreference'),
        ('api', '0029_creditcard_card_name'),
    ]

    operations = [
    ]
