# Generated by Django 2.2 on 2022-10-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_merge_20221005_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_number',
            field=models.IntegerField(default=0),
        ),
    ]
