# Generated by Django 2.2 on 2022-10-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_userstories'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_expired',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
