# Generated by Django 2.2 on 2022-10-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20221005_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(default='', max_length=32),
        ),
    ]
