# Generated by Django 2.2 on 2022-10-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20221018_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='userBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_type', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('audio', models.FileField(null=True, upload_to='None')),
                ('video', models.FileField(null=True, upload_to='None')),
                ('photos', models.ImageField(null=True, upload_to='None')),
            ],
            options={
                'db_table': 'bookmark',
            },
        ),
    ]
