# Generated by Django 2.2 on 2022-10-18 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_userbookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_bookmarks',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_push_notification', models.BooleanField(default=False)),
                ('show_full_text', models.BooleanField(default=False)),
                ('monthly_news_letter', models.BooleanField(default=False)),
                ('new_posts_summary', models.BooleanField(default=False)),
                ('new_posts_summary_time', models.IntegerField()),
                ('new_stream', models.BooleanField(default=False)),
                ('upcoming_stream_reminder', models.BooleanField(default=False)),
                ('new_private_msg_summary', models.BooleanField(default=False)),
                ('new_private_msg_summary_time', models.IntegerField()),
                ('receive_less_notification', models.BooleanField(default=False)),
                ('subscription_notification', models.BooleanField(default=False)),
                ('new_comment', models.BooleanField(default=True)),
                ('new_like', models.BooleanField(default=True)),
                ('discount_from_users', models.BooleanField(default=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Language')),
            ],
        ),
        migrations.DeleteModel(
            name='userBookmark',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='discount_from_users',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='monthly_news_letter',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='new_comment',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='new_like',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='new_posts_summary',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='new_private_msg_summary',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='new_stream',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='push_notification',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='receive_less_notification',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='show_full_text',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='subscription_notification',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='upcoming_stream_reminder',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discount_from_users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='user',
            name='monthly_news_letter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_posts_summary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_private_msg_summary',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_stream',
        ),
        migrations.RemoveField(
            model_name='user',
            name='push_notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='receive_less_notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='show_full_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_notification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upcoming_stream_reminder',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbookmarks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_bookmark', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userbookmarks',
            index=models.Index(fields=['id'], name='user_bookma_id_c27a61_idx'),
        ),
    ]
