# Generated by Django 2.2 on 2022-10-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20221018_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='new_posts_summary_time',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='new_private_msg_summary_time',
            field=models.IntegerField(blank=True),
        ),
    ]
