# Generated by Django 2.2 on 2022-10-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20221018_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbookmarks',
            old_name='type',
            new_name='bookmark_type',
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='enable_email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
