# Generated by Django 2.2 on 2022-10-19 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20221018_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookmarks',
            name='bookmark_type',
        ),
        migrations.RemoveField(
            model_name='userbookmarks',
            name='title',
        ),
        migrations.AddField(
            model_name='userbookmarks',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookmark_post', to='api.Posts'),
        ),
    ]
