# Generated by Django 2.2 on 2022-10-19 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20221019_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmarks',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Posts'),
        ),
    ]
