# Generated by Django 2.2 on 2022-10-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20221019_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmarks',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookmark_post', to='api.Posts'),
        ),
    ]
