# Generated by Django 2.2 on 2022-11-02 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_confineusers_usercustomgroupmembers_usercustomlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmarks',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_post', to='api.Posts'),
        ),
        migrations.AlterField(
            model_name='userbookmarks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
