# Generated by Django 2.2 on 2022-11-09 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20221105_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmarks',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
