# Generated by Django 2.2 on 2022-12-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_userbookaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookaccounts',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
