# Generated by Django 2.2 on 2022-12-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_userbookaccounts_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookaccounts',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
