# Generated by Django 2.2 on 2022-12-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20221212_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferwisedetails',
            old_name='abrotn',
            new_name='abartn',
        ),
        migrations.RenameField(
            model_name='transferwisedetails',
            old_name='account_holder_name',
            new_name='accountHolderName',
        ),
        migrations.RenameField(
            model_name='transferwisedetails',
            old_name='account_number',
            new_name='accountNumber',
        ),
        migrations.RenameField(
            model_name='transferwisedetails',
            old_name='first_line',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='transferwisedetails',
            old_name='postcode',
            new_name='postCode',
        ),
        migrations.AddField(
            model_name='transferwisedetails',
            name='firstLine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
