# Generated by Django 2.2 on 2022-12-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20221212_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferwisedetails',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
