# Generated by Django 2.2 on 2022-12-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_transferwisedetails_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferwisedetails',
            name='receipt_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
