# Generated by Django 2.2 on 2022-12-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_transferwisedetails_receipt_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransferWiseDetails',
            new_name='UserRecepientAccount',
        ),
    ]
