# Generated by Django 2.2 on 2022-12-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20221213_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecepientaccount',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
