# Generated by Django 2.2 on 2022-12-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20221213_0722'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userrecepientaccount',
            index=models.Index(fields=['id'], name='recepient_a_id_7c166c_idx'),
        ),
        migrations.AlterModelTable(
            name='userrecepientaccount',
            table='recepient_accounts',
        ),
    ]
