# Generated by Django 2.2 on 2022-12-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20221228_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='wallet_address',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
