# Generated by Django 2.2 on 2023-01-18 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20221230_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiseRecepients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountHolderName', models.CharField(max_length=255)),
                ('accountNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('abartn', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('postCode', models.IntegerField()),
                ('firstLine', models.CharField(blank=True, max_length=255, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transferwise_recepients',
            },
        ),
        migrations.CreateModel(
            name='WiseQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceCurrency', models.CharField(blank=True, max_length=20, null=True)),
                ('targetCurrency', models.CharField(blank=True, max_length=20, null=True)),
                ('sourceAmount', models.CharField(blank=True, max_length=250, null=True)),
                ('quote_id', models.CharField(blank=True, max_length=250, null=True)),
                ('guid', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transferwise_quotes',
            },
        ),
        migrations.CreateModel(
            name='WisePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=55)),
                ('transfer_id', models.CharField(blank=True, max_length=55, null=True)),
                ('quote_id', models.CharField(blank=True, max_length=250, null=True)),
                ('quote_uuid', models.CharField(blank=True, max_length=250, null=True)),
                ('customerTransactionId', models.CharField(blank=True, max_length=250, null=True)),
                ('receipt_id', models.CharField(blank=True, max_length=55, null=True)),
                ('transferPurpose', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transferwise_payments',
            },
        ),
        migrations.AddIndex(
            model_name='wiserecepients',
            index=models.Index(fields=['id'], name='transferwis_id_3bc592_idx'),
        ),
        migrations.AddIndex(
            model_name='wisequotes',
            index=models.Index(fields=['id'], name='transferwis_id_d3ec0b_idx'),
        ),
        migrations.AddIndex(
            model_name='wisepayments',
            index=models.Index(fields=['id'], name='transferwis_id_5a6fd3_idx'),
        ),
    ]
