# Generated by Django 2.2 on 2023-01-31 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_auto_20230118_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, max_length=20, null=True)),
                ('expiry', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_identity',
            },
        ),
        migrations.AddIndex(
            model_name='useridentity',
            index=models.Index(fields=['id'], name='user_identi_id_2b6b32_idx'),
        ),
    ]
