# Generated by Django 2.2 on 2023-01-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20230131_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useridentity',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
