# Generated by Django 2.2 on 2023-01-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20230131_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useridentity',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useridentity',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='useridentity',
            name='postcode',
        ),
        migrations.AddField(
            model_name='useridentity',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
