# Generated by Django 2.2 on 2023-01-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20230131_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='useridentity',
            name='documentNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
