# Generated by Django 2.2 on 2023-02-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20230203_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='connections',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='connections',
            field=models.IntegerField(default=0),
        ),
    ]
