# Generated by Django 2.2 on 2023-02-06 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20230203_0520'),
        ('api', '0079_auto_20230131_0915'),
    ]

    operations = [
    ]
