# Generated by Django 2.2 on 2023-02-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_merge_20230206_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useridentity',
            name='age',
        ),
        migrations.AddField(
            model_name='useridentity',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
