# Generated by Django 2.2 on 2023-02-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_useridentity_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='verify_email_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_email_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
