# Generated by Django 2.2 on 2023-02-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20230209_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useridentity',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
