# Generated by Django 2.2 on 2023-02-14 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20230213_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBankAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountHolderName', models.CharField(max_length=255)),
                ('accountNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('postCode', models.IntegerField()),
                ('firstLine', models.CharField(blank=True, max_length=255, null=True)),
                ('primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserBankAccounts',
            },
        ),
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountHolderName', models.CharField(max_length=255, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('postCode', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserPayouts',
            },
        ),
        migrations.AddIndex(
            model_name='userbankaccounts',
            index=models.Index(fields=['id'], name='UserBankAcc_id_3e2e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='payouts',
            index=models.Index(fields=['id'], name='UserPayouts_id_4c5a3c_idx'),
        ),
    ]
