# Generated by Django 2.2 on 2023-02-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20230214_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='enable_to_be_found',
            field=models.BooleanField(default=False),
        ),
    ]
