# Generated by Django 2.2 on 2023-02-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_userpreferences_enable_to_be_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='enable_to_be_found',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='able_to_be_found',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='able_to_be_found',
            field=models.BooleanField(default=False),
        ),
    ]
