# Generated by Django 2.2 on 2023-02-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20230215_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalposts',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
    ]
