# Generated by Django 2.2 on 2023-02-17 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_auto_20230215_0631'),
        ('api', '0086_auto_20230215_1612'),
    ]

    operations = [
    ]
