# Generated by Django 2.2 on 2023-02-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_merge_20230217_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='subscribe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_subscribe', to='api.UserSubscription'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type_of_notification',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
