# Generated by Django 2.2 on 2023-02-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_auto_20230217_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalposts',
            name='amount',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='amount',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
