# Generated by Django 2.2 on 2023-02-17 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20230217_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='api.Posts')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_payment',
            },
        ),
        migrations.AddIndex(
            model_name='postspayment',
            index=models.Index(fields=['id'], name='post_paymen_id_892e17_idx'),
        ),
    ]
