# Generated by Django 2.2 on 2023-02-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_auto_20230222_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='subscribe',
        ),
    ]
