# Generated by Django 2.2 on 2023-02-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_merge_20230217_0351'),
        ('api', '0092_auto_20230217_0735'),
    ]

    operations = [
    ]
