# Generated by Django 2.2 on 2023-02-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_auto_20230222_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='message',
        ),
    ]
