# Generated by Django 2.2 on 2023-02-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_merge_20230221_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='postspayment',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_message', to='api.Messages'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='type_of_notification',
            field=models.CharField(blank=True, max_length=264, null=True),
        )
    ]
