# Generated by Django 2.2 on 2023-02-22 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_notifications_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='followrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_followrequest', to='api.UserFollowers'),
        ),
    ]
