# Generated by Django 2.2 on 2023-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_auto_20230221_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposts',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
