# Generated by Django 2.2 on 2023-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_auto_20230221_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postspayment',
            name='status_success',
            field=models.BooleanField(default=False),
        ),
    ]
