# Generated by Django 2.2 on 2023-02-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_auto_20230221_0937'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userstories',
            index=models.Index(fields=['id'], name='user_storie_id_d12a11_idx'),
        ),
        migrations.AlterModelTable(
            name='userstories',
            table='user_stories',
        ),
    ]
