# Generated by Django 2.2 on 2023-02-22 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_auto_20230222_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStoriesLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'story_likes',
            },
        ),
        migrations.AddField(
            model_name='userstorieslikes',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_story', to='api.UserStories'),
        ),
        migrations.AddField(
            model_name='userstorieslikes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userstorieslikes',
            index=models.Index(fields=['id'], name='story_likes_id_ff03d0_idx'),
        ),
    ]
