# Generated by Django 2.2 on 2023-02-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_auto_20230222_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        )
    ]
