# Generated by Django 2.2 on 2023-02-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_notifications_followrequest'),
        ('api', '0103_auto_20230223_1021'),
    ]

    operations = [
    ]
