# Generated by Django 2.2 on 2023-02-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_merge_20230224_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='followrequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_followrequest', to='api.UserFollowers'),
        ),
    ]
