# Generated by Django 2.2 on 2023-02-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20230227_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
