# Generated by Django 2.2 on 2023-03-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20230302_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='user_wallet_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_wallet_balance',
            field=models.IntegerField(default=0),
        ),
    ]
