# Generated by Django 2.2 on 2023-03-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20230306_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='user_wallet_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_wallet_balance',
        ),
    ]