# Generated by Django 2.2 on 2023-03-20 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_auto_20230307_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmessages',
            name='media',
        ),
        migrations.RemoveField(
            model_name='historicalmessages',
            name='type',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='media',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='type',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='user_wallet_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='user_wallet_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostCommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.PostComments')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
