# Generated by Django 2.2 on 2023-03-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_auto_20230320_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='wallet_address',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
